-- phpMyAdmin SQL Dump
-- version 4.1.12
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 18, 2016 at 09:35 AM
-- Server version: 5.5.36
-- PHP Version: 5.4.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `ecommerce`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE IF NOT EXISTS `cart` (
  `p_id` int(10) NOT NULL,
  `ip_add` varchar(255) NOT NULL,
  `qty` int(10) NOT NULL,
  PRIMARY KEY (`p_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cart`
--

INSERT INTO `cart` (`p_id`, `ip_add`, `qty`) VALUES
(27, '::1', 0),
(30, '::1', 0),
(34, '::1', 0),
(35, '::1', 0),
(48, '::1', 0);

-- --------------------------------------------------------

--
-- Table structure for table `catagories`
--

CREATE TABLE IF NOT EXISTS `catagories` (
  `cat_id` int(100) NOT NULL AUTO_INCREMENT,
  `cat_title` text NOT NULL,
  PRIMARY KEY (`cat_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;

--
-- Dumping data for table `catagories`
--

INSERT INTO `catagories` (`cat_id`, `cat_title`) VALUES
(1, 'Air Frier'),
(2, 'Electric Jug/Kettle'),
(3, 'Rice Cooker'),
(4, 'Electric Oven/Microwave Oven'),
(5, 'Sandwich Maker'),
(6, 'Griller'),
(7, 'Toaster'),
(8, 'Induction'),
(10, 'E-Pressure Cooker'),
(11, 'D-Frier');

-- --------------------------------------------------------

--
-- Table structure for table `catagories2`
--

CREATE TABLE IF NOT EXISTS `catagories2` (
  `cat2_id` int(100) NOT NULL AUTO_INCREMENT,
  `cat2_title` text NOT NULL,
  PRIMARY KEY (`cat2_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;

--
-- Dumping data for table `catagories2`
--

INSERT INTO `catagories2` (`cat2_id`, `cat2_title`) VALUES
(1, 'Mixer Grinder'),
(4, 'Water Dispenser'),
(6, 'Gyser/Immersion Rod'),
(7, 'Hand Blender/Chopper'),
(8, 'Water Purifier'),
(9, 'Gas Stove'),
(10, 'Dinner Sets'),
(11, 'Kitchen Tools');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `product_id` int(100) NOT NULL AUTO_INCREMENT,
  `product_cat` int(100) NOT NULL,
  `product_cat2` int(100) NOT NULL,
  `product_title` varchar(255) NOT NULL,
  `product_price` int(100) NOT NULL,
  `product_desc` text NOT NULL,
  `product_image` text NOT NULL,
  `product_keywords` text NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=56 ;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_cat`, `product_cat2`, `product_title`, `product_price`, `product_desc`, `product_image`, `product_keywords`) VALUES
(1, 1, 0, 'Koryo-Air Frier', 6990, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Timer with auto shutoff, indicator light and warning bell sound</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Comes with 2 operating jog wheel dial - one for time (upto 30 mins) and other for temperature (80-200 degrees)</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Dishwasher safe parts for easy cleaning</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Uses high speed air circulation to cook food in a healthy way with 80 percent less oil</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Capacity: 3.2 liters</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 1425 watts; Operating voltage: 220-240 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Air Fryer, Instructional Manual, Customer Care List and Gaurantee Card</span></li>\r\n</ul>', 'air frier(koryo).jpg', 'air frier,koryo'),
(4, 2, 0, 'Pigeon Electric Kettle', 999, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">360 degree rotation corded kettle</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Not concealed wiring, on and off switch</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cool handle touch</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Easy to pour and shows water level indication</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Capacity: 1 litre</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 1000 watts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Electric Kettle</span></li>\r\n</ul>', 'Jug(pigeon).jpg', 'kettle'),
(5, 3, 0, 'Bajaj Rice Cooker', 1600, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">1.8-Litre capacity</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">The cooking bowl is aluminum with anodized finish</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">1 KG Raw rice cooking capacity</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cool touch handles</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Stainless steel lid with steam vents</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Automatic cooking</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 2 years on product</span></li>\r\n</ul>', 'rice(bajaj).jpg', 'rice cooker,bajaj'),
(6, 0, 0, 'Philips-Air Frier', 7229, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Timer with ready signal and auto shutoff</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cord storage keeps kitchen surface neat and tidy</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Dishwasher-safe parts for easy cleaning</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Adjustable temperature control for the perfect result</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Rapid air technology fries the tastiest food without the oil</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Recipe booklet full of inspiring recipes and tips and tricks</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 2 years on product</span></li>\r\n</ul>', 'Air (Philips).jpg', 'air frier,philips'),
(8, 0, 0, 'Huan Yi-Electric BBQ', 2600, '<ul>\r\n<li><span style="color: #111111; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px;">Huan Yi Compact Electric BBQ.</span></li>\r\n<li><span style="color: #111111; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px;">Grill and Tandoor.</span></li>\r\n<li><span style="color: #111111; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px;">Frying and Roasting Function.</span></li>\r\n<li><span style="color: #111111; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px;">3 years warrenty.</span></li>\r\n</ul>', 'BBQ(huan).jpg', 'BBQ,huan yi'),
(26, 2, 0, 'Delonghi Electric Kettle (Red)', 3500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Unique high gloss finish with chromed details</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">1.7 litre capacity and 360 degree swivel base</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Detachable base for cord-free convenience</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Water level indicator and flat stainless steel concealed element</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">3-level safety protection-auto shut-off when water begins to boil, thermal cut-off and auto shut-off when body is lifted from base</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Removable, washable scale filter and cord storage</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 years on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 2000 Watts</span></li>\r\n</ul>', 'Delonghi(kettle).jpg', 'kettle'),
(27, 2, 0, 'Bajaj 1.7-Li Kettle', 1500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cordless operation</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Auto shut off</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">External water level indicator on both sides</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Self illuminated transparent switch</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Dry boil safe</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 2 years on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 1800 watts; Operating voltage: 230 volts</span></li>\r\n</ul>', 'kettle(bajaj).jpg', 'kettle'),
(28, 2, 0, 'NEXT 1.5L KETTLE ', 1200, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">AUTO CUT-OFF</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">1500 W , 1.5 LITRE , CONCEALED ELEMENT</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">220-240V , 50/60Hz</span></li>\r\n</ul>', 'kettle(next gen).jpg', 'kettle'),
(29, 1, 0, 'Philips- Air Frier', 3999, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Timer with ready signal and auto shutoff</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cord storage keeps kitchen surface neat and tidy</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Dishwasher-safe parts for easy cleaning</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Adjustable temperature control for the perfect result</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Rapid air technology fries the tastiest food without the oil</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Recipe booklet full of inspiring recipes and tips and tricks</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 2 years on product</span></li>\r\n</ul>', 'Air (Philips).jpg', 'air frier,philips'),
(30, 1, 0, 'Kenstar-Air Frier', 4500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Handle for easy carrying</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Thermostat and timer dials</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">3 litre Frying Basket</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 2 years on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 1500 watts; Operating Voltage: 220-240 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Oxy Fryer and Recipe book</span></li>\r\n</ul>', 'air frier(kenstar).jpg', 'air frier'),
(31, 1, 0, 'Havells-Air Frier', 3500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">With the unique Rapid air technology, Havells Airfryer lets you fry, bake, toast, roast, grill and reheat the food with hot air making it up to 85% less oily over traditional deep frying.</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Havells Air fryers comes with an integrated auto-off timer and temperature control function. These enable faster cooking ensuring best results.</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">With large cooking capacity, Havells air frying basket comes with a separator that lets you cook multiple food items simultaneously saving time and energy.</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">2-Litre large food basket</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">4-Litre extra large pan capacity</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Food grade aluminium non-stick coated food basket</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Oil free cooking-healthy and hygenic</span></li>\r\n</ul>', 'air frier(Havells).jpg', 'air frier'),
(32, 3, 0, 'Prestige-Rice cooker', 2799, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Aluminum cooking pan</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Detachable power cord</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Condensation cup</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Steamer basket</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Strong body</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 500 watts; Operating voltage: 220-240 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Rice cooker, Instruction manual and Warranty card</span></li>\r\n</ul>', 'rice(prestige).jpg', 'rice cooker'),
(33, 3, 0, 'Panasonic-Rice cooker', 2499, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 230 watts; Operating voltage: 220-240 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Rice cooker, Manual book and Warranty card</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Capacity (After Cooking): 0.5 Litre</span></li>\r\n</ul>', 'rice(panasaonic).jpg', 'rice cooker'),
(34, 3, 0, 'Panasonic-Automatic Rice Cooker ', 3599, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Convenient bridge handle</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Auto cooking/scoop holder</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">4 hours keep warm function</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Clear steaming basket</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Lid holder</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Anchor coated non-stick cooking pan</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 2 years on product and 5 years on heater</span></li>\r\n</ul>', 'rice(panasonic2).jpg', 'rice cooker'),
(35, 4, 0, 'IFB-Microwave 20li', 4999, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Stainless steel cavity and LED display with clock</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">10 power levels and 10 temperature levels</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Grill, microwave and convection</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Speed defrost and multi stage cooking</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">24 auto cook menus</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Express cooking quick start, auto reheat, keep warm and child safety lock</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on machine, 3 years on Magnetron and Cavity</span></li>\r\n</ul>', 'wave(ifb).jpg', 'microwave'),
(37, 4, 0, 'LG-Microwave', 3600, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">131 auto cook menu with 87 Indian menu and quick defrost</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Child lock and membrane control type</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">5 power levels and stainless steel cavity</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Two stage cooking and cooking completion alarm</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Intellowave technology and red chic door design</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Next step guide</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n</ul>', 'wave(lg).jpg', 'microwave'),
(38, 4, 0, 'Godrej-Microwave', 6999, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">141 insta-cook menus</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Combination and preset cooking</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Auto protection &amp;10 power levels</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product and 3 years on magnetron</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 2200 watts; Operating voltage: 230 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Microwave oven, Glass turn table, Roller ring, Grill stand and User manual with warranty card</span></li>\r\n</ul>', 'wave(godrej).jpg', 'microwave'),
(39, 5, 0, 'Prestige-Sandwich Maker', 2200, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Fixed grill plates</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Non-stick heating plate</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Elegant black finish body</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 800 watts; Operating voltage: 220-240 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Sandwich toaster, Instruction manual and Warranty card</span></li>\r\n</ul>', 'sandwich(prestige).jpg', 'sandwich maker'),
(40, 5, 0, 'NOVA-Sandwich Maker', 2900, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Adjustable temperature with barbeque grill</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">3 in 1 panni grill press with adjustable temperature control</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">3 in 1 function</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 2000 watts; Operating voltage: 210-250 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Sandwich maker and instruction manual</span></li>\r\n</ul>', 'sandwich(nova).jpg', 'sandwich maker'),
(41, 6, 0, 'Prestige-Griller', 2200, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Quick to assemble</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Coal based cooking</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Detachable legs</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Portable case</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Easy to clean</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n</ul>', 'griller.jpg', 'griller'),
(42, 7, 0, 'Bajaj-Toaster', 2200, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">2 slice capacity and auto pop up</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cool touch body and variable browning control</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Mid cycle cancel, reheat and defrost function</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Extra wide slots for thick bread slice</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Extra lift for small size bread slices</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Bread slice centering device for even toasting</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Easy slide out crumb tray and cord storage</span></li>\r\n</ul>', 'toaster.jpg', 'toaster'),
(43, 8, 0, 'Prestige-Induction Ccoker', 4500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Programmed for Indian cooking</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Touch start for ease of use</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">0 to 3 hours time setting</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Auto-off program cooks food safely</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">More comfortable cooking without flame</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cool-to-touch surface cooks foods safely</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n</ul>', 'induction.jpg', 'induction'),
(48, 11, 0, 'Usha-Deep frier', 3500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Precision cooking: Deep frying</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Cool touch body and capacity: 1.5 liter</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Frying basket with cool touch handle</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Elegant stainless steel finish</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Adjustable thermostat control</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Detachable oil pot non-stick coating</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Detachable lid with viewing window</span></li>\r\n</ul>', 'deep.jpg', 'deep frier'),
(49, 10, 0, 'Usha E-pressure cooker', 3500, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Efficient, fast and saves time</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Electronically controlled precision cooking</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Preserves essential nutrients in food</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Variable food cooking options</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Non stick teflon coating on pot</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Electric pressure cooker with capacity : 4 Litres</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">10 in built safety features</span></li>\r\n</ul>', 'e rice.jpg', 'e pressure cooker'),
(50, 0, 1, 'Philips-Juicer mixer', 3699, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Reverse spiral sieve for maximum extraction</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Unique micro mesh filter for maximim juice extraction</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Compact design for less storage space</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Easy to pour and store in separate chamber with spout</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Fruit filter for seeds and skin separation</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Blender jar with filter for soft fruits</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Centrifugal juicer for hard fruits</span></li>\r\n</ul>', 'mixer.jpg', 'mixer'),
(51, 0, 4, 'Voltas-water dispenser', 4100, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">With refrigerator</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">3 temperature taps - Hot, plain and cold. 3 liter cooling and 5 liter heating capacity per hour.</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Body made of ABS plastic and tank made of Food grade stainless steel. Heavy duty bottle piercer with bottle holder.</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Color - White and blue .</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">1 year warranty</span></li>\r\n</ul>', 'dispenser.jpg', 'dispenser'),
(52, 0, 6, 'Bajaj-heating rod', 900, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Anti-corrosive Material</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Hairpin tubular elements</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Consumes less energy</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Best heating option at lowest cost</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 1500 watts</span></li>\r\n</ul>', 'rod.jpg', 'immersion rod'),
(53, 0, 7, 'Glen-mini chopper', 2000, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Small compact size capacity 400 ml</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Food grade transparent PC bowl for clear visibility</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Plus start</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Rust resistant stainless steel blades</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Non-slip ring for stability</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Warranty: 1 year on product</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Power: 250 watts; Operating voltage: 210-250 volts</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Includes: Mini chopper, Instruction manual and Warranty card</span></li>\r\n</ul>', 'chopper.jpg', 'chopper');
INSERT INTO `products` (`product_id`, `product_cat`, `product_cat2`, `product_title`, `product_price`, `product_desc`, `product_image`, `product_keywords`) VALUES
(54, 0, 9, 'Pigeon-Gas stove', 3500, '<p>&nbsp;</p>\r\n<div id="featurebullets_feature_div" class="feature" style="box-sizing: border-box; color: #111111; font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;" data-feature-name="featurebullets">\r\n<div id="feature-bullets" class="a-section a-spacing-medium a-spacing-top-small" style="box-sizing: border-box; margin-top: 10px !important; margin-bottom: 0px;">\r\n<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Unique toughened glass</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Spill proof design</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">High thermal efficiency</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Uniquely designed pan</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Designer knobs</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Easy to clean</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">Package contents: 1-Piece 3 Burner LPG Stove Base, 3-Pieces Brass Burner and 3-Pieces Vessel Stand</span></li>\r\n</ul>\r\n</div>\r\n</div>', 'stove.jpg', 'gas stove'),
(55, 0, 10, 'Nayasa-Dinner set', 1200, '<ul class="a-vertical a-spacing-none" style="box-sizing: border-box; color: #949494; padding: 0px; font-family: Arial, sans-serif; font-size: 13px; line-height: 19px; margin: 0px 0px 0px !important 18px;">\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">dishwasher safe for easy cleaning</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">microwave safe</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">freezer safe</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">beautiful floral print</span></li>\r\n<li style="box-sizing: border-box; list-style: disc; word-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: #111111;">BPA Free</span></li>\r\n</ul>', 'set.jpg', 'dinner set');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
